name: __PROJECTNAMEIDENTIFIER___

options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 15.0
  postGenCommand: |
    make version

configs:
  Debug: debug
  Release: release

settings:
  base:
    # Project
    SWIFT_VERSION: 5
    SDKROOT: iphoneos
    ENABLE_USER_SCRIPT_SANDBOXING: 'NO'
    SWIFT_EMIT_LOC_STRINGS: 'NO'
    LOCALIZED_STRING_SWIFTUI_SUPPORT: 'NO'
    PRODUCT_BUNDLE_IDENTIFIER: com.edyuto.$(PRODUCT_NAME)
    PRODUCT_NAME: $(TARGET_NAME)

    # Target
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    TARGET_DEVICE_FAMILY: '1'
    
    # Signing
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: iPhone Developer
    DEVELOPMENT_TEAM: 2X5PWXY74F
    PROVISIONING_PROFILE:
    PROVISIONING_PROFILE_SPECIFIER:
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      ENABLE_TESTABILITY: 'YES'
      ONLY_ACTIVE_ARCH: 'YES'
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  __PROJECTNAMEIDENTIFIER___:
    type: application
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER___]
    postBuildScripts:
      - script: ./Scripts/swiftlint
        name: SwiftLint
        basedOnDependencyAnalysis: NO
    settings:
      base:
        INFOPLIST_FILE: __PROJECTNAMEIDENTIFIER___/Resources/Info.plist

  __PROJECTNAMEIDENTIFIER___Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER___Tests]
    dependencies:
    - target: __PROJECTNAMEIDENTIFIER___
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/__PROJECTNAMEIDENTIFIER___.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/__PROJECTNAMEIDENTIFIER___

  __PROJECTNAMEIDENTIFIER___UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER___UITests]
    dependencies:
    - target: __PROJECTNAMEIDENTIFIER___
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_TARGET_NAME: __PROJECTNAMEIDENTIFIER___
