name: __PROJECTNAMEIDENTIFIER__

options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 15.0

configs:
  Debug: debug
  Release: release

settings:
  base:
    # Project
    SWIFT_VERSION: 5
    SDKROOT: iphoneos
    ENABLE_USER_SCRIPT_SANDBOXING: 'NO'
    SWIFT_EMIT_LOC_STRINGS: 'NO'
    LOCALIZED_STRING_SWIFTUI_SUPPORT: 'NO'
    PRODUCT_BUNDLE_IDENTIFIER: __PROJECTBUNDLEPREFIX__.$(PRODUCT_NAME)
    PRODUCT_NAME: $(TARGET_NAME)
    STRIP_INSTALLED_PRODUCT: 'NO'
    ALWAYS_SEARCH_USER_PATHS: 'NO'

    # Target
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    TARGET_DEVICE_FAMILY: '1'
    
    # Signing
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: iPhone Developer
    DEVELOPMENT_TEAM: __PROJECTDEVELOPMENTTEAM__
    PROVISIONING_PROFILE:
    PROVISIONING_PROFILE_SPECIFIER:
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      ENABLE_TESTABILITY: 'YES'
      ONLY_ACTIVE_ARCH: 'YES'
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

projectReferences:
  Cache:
    path: Modules/Cache/Cache.xcodeproj
  Logger:
    path: Modules/Logger/DebugLogger.xcodeproj
  Network:
    path: Modules/Network/Network.xcodeproj

targets:
  __PROJECTNAMEIDENTIFIER__:
    type: application
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER__]
    dependencies:
      - target: Cache/CacheProvider
      - target: Logger/DebugLoggerProvider
      - target: Network/NetworkProvider
    postBuildScripts:
      - script: chmod +x ./Scripts/lint-checker
        name: Lint permissions
        basedOnDependencyAnalysis: false
      - script: ./Scripts/lint-checker
        name: SwiftLint
        basedOnDependencyAnalysis: false
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: 'AppIcon'
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        INFOPLIST_FILE: __PROJECTNAMEIDENTIFIER__/Resources/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"

  __PROJECTNAMEIDENTIFIER__Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER__Tests]
    dependencies:
    - target: __PROJECTNAMEIDENTIFIER__
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        BUNDLE_LOADER: $(TEST_HOST)
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/__PROJECTNAMEIDENTIFIER__.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/__PROJECTNAMEIDENTIFIER__

  __PROJECTNAMEIDENTIFIER__UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [__PROJECTNAMEIDENTIFIER__UITests]
    dependencies:
    - target: __PROJECTNAMEIDENTIFIER__
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
        GENERATE_INFOPLIST_FILE: 'YES'
        TEST_TARGET_NAME: __PROJECTNAMEIDENTIFIER__
  
schemes:
  __PROJECTNAMEIDENTIFIER__:
    build:
      targets:
        __PROJECTNAMEIDENTIFIER__: all
        __PROJECTNAMEIDENTIFIER__Tests: [test]
        __PROJECTNAMEIDENTIFIER__UITests: [test]
        Cache/CacheProvider: [test]
        Network/NetworkProvider: [test]
    test:
      gatherCoverageData: YES
      coverageTargets:
        - __PROJECTNAMEIDENTIFIER__
        - Cache/CacheProvider
        - Network/NetworkProvider
      targets:
        - name: __PROJECTNAMEIDENTIFIER__Tests
          paralelizable: true
        - name: __PROJECTNAMEIDENTIFIER__UITests
          paralelizable: true
        - name: Cache/CacheProviderTests
          paralelizable: true
        - name: Network/NetworkProviderTests
          paralelizable: true
